services:
  postgres:
    image: 'postgres:17.2'
    environment:
      - 'POSTGRES_DB=postgres_db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    container_name: postgres-db-cnr
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@admin.admin'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    restart: always
    container_name: pgadmin-cnr
    ports:
      - 8081:80
    depends_on:
      - postgres

# this is not needed in dev mode
#  jt-engine-app:
  ##      build: .
#    image: igr025/jt-engine-21-img:v0.1
#    container_name: jt-engine-cnr
#    ports:
#      - 80:80
#    environment:
#      db-url: jdbc:postgresql://postgres-db-cnr:5432/postgres_db
#      db-username: admin
#      db-password: password
#    depends_on:
#      - postgres
#    restart: always