@template.layout.main(content = @`

<!DOCTYPE HTML>
<html lang="en">
<head>
    <title>Home</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link href="main.css" rel="stylesheet" />
</head>
<body class="bg-blue-500">
<!-- <body class="bg-slate-50"> -->
<header class="bg-white container mx-auto">
    <h1 class="text-4xl font-bold p-8">Home Page</h1>
</header>
</body>
</html>

`)